language: go
sudo: false

go:
    - 1.12.x

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go get -v -t . ./_examples
  - go test -coverprofile profile.cov .
  - go test ./_examples
  - ${GOPATH}/bin/golangci-lint run ./...
  - ${GOPATH}/bin/goveralls -coverprofile profile.cov -service=travis-ci
